dist: ./bin

before:
  hooks:
    - go mod tidy

checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'

changelog:
  filters:
    exclude:
      - '^docs'
      - '^chore'

builds:
  - id: goproxy
    main: ./cmd/goproxy
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/go-courier/goproxy/pkg/version.Version={{ .Version }}+sha.{{ .FullCommit }}
    mod_timestamp: '{{ .CommitTimestamp }}'

