name: Publish

on:
  push:
    branches:
      - "main"

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.18'

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build or Push Images
        env:
          TAG: latest
          COMMIT_SHA: ${{ github.sha }}
        run: |-
          if [[ ${{ github.ref }} == "refs/tags/v"* ]]; then
            export TAG=$(echo ${{ github.ref }} | sed -e "s/refs\/tags\/v//")
          fi
          make docker.push.goproxy